import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bluegreen: {
          50: "#DBFBF3",
          100: "#B1F6E5",
          200: "#69EDCC",
          300: "#1BE4B2",
          400: "#129675",
          500: "#094C3B",
          600: "#073B2E",
          700: "#052E24",
          800: "#042019",
          900: "#020E0B",
          950: "#010907",
        },
        mustard: {
          50: "#FFFCF0",
          100: "#FFF9DB",
          200: "#FFF4BD",
          300: "#FFEE99",
          400: "#FFE875",
          500: "#FFE353",
          600: "#FFD70F",
          700: "#CCAA00",
          800: "#8A7300",
          900: "#423700",
          950: "#241E00",
        },
        mango: {
          50: "#FFF1EB",
          100: "#FFE7DB",
          200: "#FFCEB8",
          300: "#FEB38F",
          400: "#FE9A6C",
          500: "#FE8149",
          600: "#FE5506",
          700: "#C13E01",
          800: "#842A01",
          900: "#421500",
          950: "#1E0A00",
        },
        floral: {
          50: "#FFFFFF",
          100: "#FEFDFB",
          200: "#FEFDFB",
          300: "#FDFCF7",
          400: "#FBFAF3",
          500: "#FBFAF2",
          600: "#E3DCA5",
          700: "#CDBF5B",
          800: "#988C2F",
          900: "#4A4417",
          950: "#27240C",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
